{% set name = "taxidtools" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/taxidtools-{{ version }}.tar.gz
  sha256: 6a38e74ca5f2e293170d0b83331457092942a4b38f59b3584738e5d0a26fea7d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >=3.9

test:
  imports:
    - taxidTools
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/CVUA-RRW/taxidTools
  summary: A Python Toolkit for Taxonomy
  license: BSD-3-Clause
  license_file: LICENSE
  description: |
    taxidTools allows you to easily handle complex taxonomies 
    from different sources and perform common operations such 
    as consensus determination, finding a last common ancestor 
    or calculating node distances.
  doc_url: https://cvua-rrw.github.io/taxidTools/
  dev_url: https://github.com/CVUA-RRW/taxidTools

extra:
  recipe-maintainers:
    - gregdenay
